- name: Install Microsoft repo
  shell: |
    wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    sudo dpkg -i packages-microsoft-prod.deb
    sudo apt-get update


- name: Install .NET
  apt: 
    name: aspnetcore-runtime-8.0
    state: present

- name: Create Directory
  file:
    path: /var/www/blazorapp
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Copy App
  copy:
    src: ../../../publish/
    dest: /var/www/blazorapp
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Create systemd
  copy:
    dest: /etc/systemd/system/blazorapp.service
    content: |
      [Unit]
      Description=Blazor App
      After=network.target

      [Service]
      WorkingDirectory=/var/www/blazorapp
      ExecStart=/usr/bin/dotnet /var/www/blazorapp/BlazorApp.dll
      Restart=always
      RestartSec=10
      KillSignal=SIGINT
      SyslogIdentifier=blazorapp
      User=ubuntu
      Environment=ASPNETCORE_ENVIRONMENT=Production

      [Install]
      WantedBy=multi-user.target
  notify: 
    - Reload systemd
    - Restart blazorapp 

- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Configure Nginx
  copy: 
    dest: /etc/nginx/sites-available/blazorapp
    content: |
        server {
            listen 80;
            location / {
                proxy_pass         http://localhost:5000;
                proxy_http_version 1.1;
                proxy_set_header   Upgrade $http_upgrade;
                proxy_set_header   Connection keep-alive;
                proxy_set_header   Host $host;
                proxy_cache_bypass $http_upgrade;
            }
        }

- name: Enable config
  file: 
    src: /etc/ngix/sites-available/blazorapp
    dest: /etc/nginx/sites-enabled/blazorapp
    state: link
    force: true

- name: Remove default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
    enabled: force