name: Manual Deploy

on: 
  workflow_dispatch

jobs: 
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: '8.0.x'

      - name: Build and publish
        run: |
          dotnet publish BlazorApp.csproj -c Release -o ./publish --runtime linux-x64
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-north-1

      - name: Run Terraform
        run: |
          cd Terraform
          terraform init
          terraform apply --auto-approve
    
      - name: Get Server IP
        run: |
          cd Terraform
          echo "SERVER_IP=$(terraform output -raw server_public_ip)" >> $GITHUB_ENV

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Instal Ansible and sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible sshpass

      - name: Run Playbook
        run: |
          ls -al
          cd Ansible
          ansible-playbook -i "${{ env.SERVER_IP }}," deploy.yml \
            --user ubuntu \
            --private-key ~/.ssh/id_rsa \
            --ssh-extra-args="-o StrictHostKeyChecking=no"
